# Generated by Django 5.1.7 on 2025-03-18 21:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('species', models.CharField(choices=[('CAT', 'Cat'), ('DOG', 'Dog')])),
                ('breed', models.CharField(blank=True, choices=[('Cats', [('MAINE_COON', 'Maine Coon'), ('EUROPEAN', 'European shorthair')]), ('Dogs', [('LABRADOR', 'Labrador'), ('BORDER_COLLIE', 'Border Collie')])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='family.family')),
            ],
        ),
    ]
