# Generated by Django 5.1.7 on 2025-03-27 00:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='admins',
            field=models.ManyToManyField(related_name='admin_of_families', to=settings.AUTH_USER_MODEL),
        ),
    ]
